#!/usr/bin/python

import urwid
import json
import time
import youtube_dl
import argparse
import os.path
import sys
from youtube_dl.utils import DownloadError

class YCPConfig(object):
    def __init__(self, path):
        if os.path.isfile(path) is False:
            raise Exception("{0} does not exist.".format(path))

        self.path = path

    def get(self):
        f = open(self.path, "r")
        config = json.load(f)
        config["path"] = self.path

        return config


class DownloadLogger(object):
    def __init__(self, parent):
        self.parent = parent

    def debug(self, msg):
        pass

    def warning(self, msg):
        pass

    def error(self, msg):
        self.parent.log_error(msg)

class MusicItem(urwid.WidgetWrap):
    def __init__(self, contents, on_select=None):
        self.contents = contents
        self.on_select = on_select
        self.downloaded = False

        self._columns = urwid.Columns([urwid.Text(c) for c in contents])
        self._focusable_columns = urwid.AttrMap(self._columns, '', 'reveal_focus')

        super(MusicItem, self).__init__(self._focusable_columns)

    def selectable(self):
        return True

    def update_contents(self, contents):
        self.contents[:] = contents
        for t, (w, _) in zip(contents, self._columns.contents):
            w.set_text(t)

    def get_music_data(self):
        (artist_col, _) = self._columns.contents[0] # return (widget, options)
        (title_col, _)  = self._columns.contents[1]
        (link_col, _)   = self._columns.contents[2]

        return {"artist": artist_col.text,
                "title":  title_col.text,
                "link":   link_col.text}

    def update_data(self, data):
        if len(data) == len(self.contents):
            (artist_col, _) = self._columns.contents[0]
            artist_col.set_text(data[0])
            (title_col, _) = self._columns.contents[1]
            title_col.set_text(data[1])
            (link_col, _) = self._columns.contents[2]
            link_col.set_text(data[2])

    def is_downloaded(self, detect_file = False):
        if detect_file:
            (artist_col, _) = self._columns.contents[0]
            (title_col, _)  = self._columns.contents[1]
            filename = "{0} - {1}.mp3".format(artist_col.text, title_col.text)
            self.downloaded = os.path.isfile(filename)

        return self.downloaded

    def checkfile(self):
        if self.is_downloaded(True):
            self._focusable_columns.set_attr_map({None: 'item_downloaded'})
        else:
            self._focusable_columns.set_attr_map({None: 'item_not_downloaded'})


class MusicList(urwid.ListBox):
    def __init__(self, items):
        self.items = items
        super().__init__(self.items)

    def get_items(self):
        return self.items


class MusicListView(urwid.Frame):
    signals = ['close']
    def __init__(self, items, height):
        self.height = height

        # frame header
        self.HEADERS = ["Artist", "Title", "Link"]
        self.header = urwid.Pile([urwid.Divider('─'),
                                  urwid.AttrMap(urwid.Columns([urwid.Text(c) for c in self.HEADERS]), "column_headers"),
                                  urwid.Divider('─')])

        # frame body
        self.list_items = urwid.SimpleFocusListWalker([])
        for item in items:
            self.list_items.append(MusicItem([item["artist"], item["title"], item["link"]]))
        self.music_list = MusicList(self.list_items)
        self.check_downloaded_items()

        # frame footer
        self.HINT_TEXT = "Q/ESC: Quit    A: Add    E: Edit    X: Remove    D: Download    S: Save to file"
        self.footer = urwid.Edit(self.HINT_TEXT)

        super().__init__(self.music_list, self.header, self.footer)

    def set_footer_text(self, caption, etext = "", pos = -1):
        self.footer.set_caption(caption)
        if len(etext):
            self.footer.set_edit_text(etext)
            self.footer.set_edit_pos(pos if pos >= 0 else len(etext))

    def get_footer_text(self):
        return self.footer.get_edit_text()

    def reset_footer_text(self):
        self.footer.set_caption(self.HINT_TEXT)
        self.footer.set_edit_text("")

    def set_height(self, height):
        self.height = height

    def create_pop_up(self):
        pop_up = PopUpDialog()
        urwid.connect_signal(pop_up, 'close', lambda button: self.close_pop_up())

        return pop_up

    def add_music(self, artist, title, link):
        pos = self.find_music(artist, title)
        if pos == -1:
            self.list_items.append(MusicItem([artist, title, link]))
            self.list_items[-1].checkfile()
        else:
            self.set_focus_position(pos)

    def edit_music(self, pos, artist, title, link):
        if pos >= 0 and pos < len(self.list_items):
            self.list_items[pos].update_data([artist, title, link])
            self.list_items[pos].checkfile()

    def find_music(self, artist, title):
        """
        music key: (artist, title)
        """
        i = 0
        count = len(self.list_items)
        while i < count:
            item = self.list_items[i].get_music_data()
            if item["artist"] == artist and item["title"] == title:
                break
            i += 1

        return i if i < count else -1

    def get_item_count(self):
        return len(self.list_items)

    def get_music(self, pos):
        return self.list_items[pos].get_music_data()

    def get_all_musics(self):
        return [row.get_music_data() for row in self.list_items]

    def get_selected_item(self):
        return self.list_items[self.get_focus_position()].get_music_data()

    def get_new_items(self):
        return [row.get_music_data() for row in self.list_items if row.is_downloaded() == False]

    def get_pop_up_parameters(self):
        return {'left': 0, 'top': 1, 'overlay_width': 32, 'overlay_height': 7}

    def get_layout(self):
        return [urwid.Divider(u'─'),
                self.header,
                urwid.Divider(u'─'),
                urwid.BoxAdapter(self.music_list, self.height - 3)]

    def get_focus_position(self):
        (_, pos) = self.music_list.get_focus()
        return pos

    def set_focus_position(self, pos):
        if pos >= 0:
            self.music_list.set_focus(pos)

    def focus_top_position(self):
        pos = -1 if len(self.list_items) == 0 else len(self.list_items) - 1
        self.set_focus_position(pos)

    def remove_item(self):
        (_, pos) = self.music_list.get_focus()
        if pos >= 0:
            del self.list_items[pos]

    def check_downloaded_items(self):
        for item in self.music_list.get_items():
            item.checkfile()


class Downloader(object):
    def __init__(self, items, status_callback):
        """
        Parameters:
        item (list): A list contains items to download.
        status_callback (function): A function is called when a status is triggered.
                                    status: started, downloading, downloaded, finished, error.
        """

        self.downloading_items = items
        self.status_callback = status_callback
        self.audio_format = 'mp3'
        self.downloading_item = None

    def start(self):
        self.status_callback_hook({'status': 'started'})

        ydl_opts = {
            'format': 'bestaudio/best',
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': self.audio_format
            }],
            'logger': DownloadLogger(self),
            'progress_hooks': [self.status_callback_hook],
        }

        self.downloading_item_index = 0
        self.downloading_items_count = len(self.downloading_items)
        for item in self.downloading_items:
            self.downloading_item = item
            ydl_opts["outtmpl"] = "{0} - {1}.%(ext)s".format(item["artist"], item["title"], self.audio_format)
            try:
                with youtube_dl.YoutubeDL(ydl_opts) as ydl:
                    ydl.download([item["link"]])
            except DownloadError as e:
                self.status_callback_hook({'status': 'error'})

            self.downloading_item_index += 1

    def status_callback_hook(self, data):
        if self.downloading_item:
            data['artist']          = self.downloading_item['artist']
            data['title']           = self.downloading_item['title']
            data['link']            = self.downloading_item['link']
            data['audio_format']    = self.audio_format
            data['index'] = self.downloading_item_index
            data['count'] = self.downloading_items_count

        self.status_callback(data)

    def log_error(self, msg):
        self.status_callback_hook({'error_msg': msg})


class TUIApp(object):
    def __init__(self, config):
        self.PALETTE = [
            ("column_headers",      "white, bold",      ""),
            ("notifier_active",     "dark cyan",        "light gray"),
            ("notifier_inactive",   "black",            "dark gray"),
            ("reveal_focus",        "black",            "dark cyan", "standout"),
            ("item_downloaded",     "light green",      ""),
            ("item_not_downloaded", "light red",        "")
        ]

        # Get terminal size
        (self.terminal_cols, self.terminal_rows) = urwid.raw_display.Screen().get_cols_rows()

        self.config = config
        self.audio_format = "mp3"
        self.adding_music = False
        self.editing_music = False
        self.saving_music_list = False
        self.selecting_download_option = False
        self.item_editor_height = 4
        self.unsaved = False
        self.quiting_with_unsaved = False

        self.create_edit_dialog()
        self.create_music_list_view()

        self.main_view = urwid.Pile([('weight', self.terminal_rows - self.item_editor_height, self.music_list_view)])
        self.loop = urwid.MainLoop(self.main_view, self.PALETTE, unhandled_input = self.handle_input, pop_ups = True)

    def refresh_main_view(self, item_editor_data = None):
        self.main_view.contents.clear()
        if item_editor_data is not None:
            self.main_view.contents.append((self.item_editor, ('weight', self.item_editor_height)))
            self.artist_edit.set_edit_text(item_editor_data["artist"])
            self.title_edit.set_edit_text(item_editor_data["title"])
            self.link_edit.set_edit_text(item_editor_data["link"])
        self.main_view.contents.append((self.music_list_view, ('weight', self.terminal_rows - self.item_editor_height)))

    def create_edit_dialog(self):
        self.artist_edit = urwid.Edit(u"Artist: ", u"")
        self.title_edit = urwid.Edit(u"Title: ", u"")
        self.link_edit = urwid.Edit(u"Link: ", u"")
        save_button = urwid.Button(u"Save", lambda button : self.save_music(self.artist_edit.get_edit_text(),
                                                                            self.title_edit.get_edit_text(),
                                                                            self.link_edit.get_edit_text()))
        cancel_button = urwid.Button(u"Cancel", lambda button : self.handle_input('q'))
        self.item_editor = urwid.ListBox(urwid.SimpleFocusListWalker([self.artist_edit,
                                                                      self.title_edit,
                                                                      self.link_edit,
                                                                      urwid.Columns([save_button, cancel_button])]))

    def create_music_list_view(self):
        items = []
        if "items" in self.config:
            items = self.config["items"]
        self.music_list_view = MusicListView(items, self.terminal_rows - 1) # status bar occupies one row

    def on_edit_item(self):
        self.handle_input('e')

    def handle_input(self, key):
        if key in ('q', 'Q', 'esc'):
            if self.adding_music or self.editing_music or self.selecting_download_option:
                self.adding_music = False
                self.editing_music = False
                self.selecting_download_option = False
                self.refresh_main_view()
            elif self.saving_music_list:
                self.music_list_view.set_focus('body')
                self.saving_music_list = False
            elif self.quiting_with_unsaved:
                self.quiting_with_unsaved = False
            else:
                if self.unsaved:
                    self.set_status("Save changes to ? Y: Yes    N: No    ESC: Cancel")
                    self.quiting_with_unsaved = True
                    return
                else:
                    self.exit()

            self.reset_status()
        elif key in ('a', 'A'):
            if self.selecting_download_option:
                self.start_download_all()
            elif self.adding_music == False:
                self.adding_music = True
                self.refresh_main_view({'artist': '', 'title': '', 'link': ''})
                self.set_status("Adding music")
        elif key in ('e', 'E'):
            if self.editing_music == False:
                self.editing_music = True
                self.editing_music_pos = self.music_list_view.get_focus_position()
                data = self.music_list_view.get_music(self.editing_music_pos)
                self.refresh_main_view(data)
                self.set_status("Editing music")
        elif key in ('d', 'D'):
            self.selecting_download_option = True
            self.set_status("Download> A: All    S: Selected item    N: New items    ESC: Cancel")
        elif key in ('n', 'N'):
            if self.selecting_download_option:
                self.start_download_new_items()
            elif self.quiting_with_unsaved:
                self.exit()
        elif key in ('s', 'S'):
            if self.selecting_download_option:
                self.start_download_selected_item()
            elif self.saving_music_list == False:
                self.saving_music_list = True
                self.edit_save_file_name()
        elif key in ('x', 'X'):
            self.music_list_view.remove_item()
            self.unsaved = True
        elif key in ('y', 'Y'):
            self.save_music_list(self.config["path"])
            self.unsaved = False
            self.quiting_with_unsaved = False
            self.handle_input('q')
        elif key == 'enter':
            if self.saving_music_list:
                self.save_music_list(self.music_list_view.get_footer_text())
                self.handle_input('q')

    def save_music_list(self, file_name):
        items = self.music_list_view.get_all_musics()
        with open(file_name, "w") as f:
            json.dump({"items": items}, f, indent = 4)

        self.unsaved = False

    def save_music(self, artist, title, link):
        if self.adding_music:
            self.music_list_view.add_music(artist, title, link)
        elif self.editing_music:
            self.music_list_view.edit_music(self.editing_music_pos, artist, title, link)
        self.handle_input('q')
        self.unsaved = True

    def start_download(self, items_to_download):
        self.selecting_download_option = False
        Downloader(items_to_download, self.progress_hook).start()

    def start_download_all(self):
        self.start_download(self.music_list_view.get_all_musics())

    def start_download_selected_item(self):
        self.start_download([self.music_list_view.get_selected_item()])

    def start_download_new_items(self):
        self.start_download(self.music_list_view.get_new_items())

    def progress_hook(self, data):
        if 'error_msg' in data:
            self.set_status(data['error_msg'])
            time.sleep(8) # hang to let user see what happened
        elif 'status' in data:
            if data['status'] == 'started':
                self.set_status("preparing download......")
                time.sleep(1)

            elif data['status'] == 'downloading':
                status = "task {0}/{1}: downloading({2}) {3} - {4}.{5}, speed: {6}".format(data['index'] + 1,
                                                                                           data['count'],
                                                                                           data['_percent_str'],
                                                                                           data['artist'],
                                                                                           data['title'],
                                                                                           data['audio_format'],
                                                                                           data['_speed_str'])
                self.set_status(status)
            elif data['status'] == 'error':
                status = "task {0}/{1} failed".format(data['index'] + 1, data['count'])
                self.set_status(status)
                time.sleep(8) # hang to let user see what happened

            elif data['status'] == 'finished':
                status = "task {0}/{1}: {2} downloaded".format(data['index'], data['count'], data["filename"])
                self.set_status(status)
                time.sleep(1)
                target_filename = "{0} - {1}.{2}".format(data['artist'], data['title'], data['audio_format'])
                status = "task {0}/{1}: converting to {2}".format(data['index'] + 1,
                                                                  data['count'],
                                                                  target_filename)
                self.set_status(status)

                # wait until file has been converted sucessfully, timeout 300s.
                if not os.path.exists(target_filename):
                    with open(target_filename, 'w'): pass

                timeout = 0
                while timeout > 0 and not os.path.isfile(target_filename):
                    time.sleep(1)
                    timeout -= 1

                if (data['index'] + 1) == data['count']:
                    self.music_list_view.check_downloaded_items()
                    self.set_status("All tasks are finished.")
                    time.sleep(4)
                    self.reset_status()


    def set_status(self, caption):
        self.music_list_view.set_footer_text(caption)
        self.loop.draw_screen()

    def reset_status(self):
        self.music_list_view.reset_footer_text()

    def edit_save_file_name(self):
        self.music_list_view.set_footer_text("Save as: ", self.config["path"])
        self.music_list_view.set_focus('footer')

    def exit(self):
        raise urwid.ExitMainLoop()

    def run(self):
        self.loop.run()


class TerminalDownloader(object):
    def __init__(self, config):
        self.config = config

    def progress_hook(self, data):
        if 'error_msg' in data:
            print(data['error_msg'])
        elif 'status' in data:
            if data['status'] == 'started':
                print("preparing download......")

            elif data['status'] == 'downloading':
                status = "task {0}/{1}: downloading({2}) {3} - {4}.{5}, speed: {6}".format(data['index'] + 1,
                                                                                           data['count'],
                                                                                           data['_percent_str'],
                                                                                           data['artist'],
                                                                                           data['title'],
                                                                                           data['audio_format'],
                                                                                           data['_speed_str'])
                sys.stdout.write("\r")
                sys.stdout.write(status)
                sys.stdout.flush()
            elif data['status'] == 'error':
                print("error occured: ")
                print(data)

            elif data['status'] == 'finished':
                print("")


    def start(self):
        Downloader(config['items'], self.progress_hook).start()
    

if __name__ == '__main__':
    ap = argparse.ArgumentParser(description = 'Download youtube videos as audios')
    ap.add_argument('-f', dest = 'configpath', action = 'store', default = 'ycp.json')
    ap.add_argument('-d', dest = 'download_directly', action = 'store_true')
    args = ap.parse_args()

    config = YCPConfig(args.configpath).get()

    if args.download_directly:
        TerminalDownloader(config).start()
    else:
        TUIApp(config).run()
